In [2]:
print('hello world')

hello world

In [6]:
person = { 'name': '홍길동', 'age': 10 }
# 요소추가
person['gender'] = '남자'
print(person)
# 요소 수정
person['age'] = 20
print(person)
del person['gender']
print(person)
#  함수, 메소드 설명 보기 help 함수 이용
help(person.clear)

{'name': '홍길동', 'age': 10, 'gender': '남자'}
{'name': '홍길동', 'age': 20, 'gender': '남자'}
{'name': '홍길동', 'age': 20}
Help on built-in function clear:

clear(...) method of builtins.dict instance
    D.clear() -> None.  Remove all items from D.

In [16]:
# 딕셔너리에서 키값 가져오기
(person.keys())
# 타입 확인하기 : 내장함수 type을 사용
print(type(person.keys()))

# 딕셔너리에서 값만 가져오기
print(person.values())
print(type(person.values()))

# 딕셔너리에서 아이템 (키, 값) 가져오기
print(person.items())
print(type(person.items()))

#  딕셔너리의 키 순회하기
for k in person.keys():
  print(k)

#  딕셔너리의 값 순회하기
for v in person.values():
  print(v)

#  딕셔너리의 아이템 순회하기
for i in person.items():
  print(i)

#  딕셔너리의 키 순회하기
for k,v in person.items():
  print(f'{k}-{v}')

# 튜플은 개별 변수에 저장하기
name, age, gender = ('홍길동', 30, '남자')

<class 'dict_keys'>
dict_values(['홍길동', 20])
<class 'dict_values'>
dict_items([('name', '홍길동'), ('age', 20)])
<class 'dict_items'>
name
age
홍길동
20
('name', '홍길동')
('age', 20)
name-홍길동
age-20

In [25]:
print(person['name'])
print(person.get('name'))
# print(person['gender'])
print(person.get('gender'))
print(person.get('gender', '남자'))

#  딕셔너리에 키 존재 여부 확인 in
print('gender' in person)
print('name' in person)

홍길동
홍길동
None
남자
False
True

In [26]:
s1 = {1, 2, 3}
s2 = set([3, 4, 5])

print(s1, s2)

# 교집합
intersection = s1 & s2
print(inter)

{1, 2, 3} {3, 4, 5}

In [28]:
x = 10;

print(x)

id(x)

10

137019489927696

In [31]:
def calculate(x, y) :
  add = x + y
  difference = x - y
  multifly = x * y
  mod = x // y
  remain = x % y
  return add, difference, multifly, mod, remain

print(sum(10, 30))

print(type(calculate(10, 3)))

add, difference, multifly, mod, remain = calculate(10, 3)
print(add, difference, multifly, mod, remain )

40
<class 'tuple'>
13 7 30 3 1

In [34]:
 pocket = ['paper', 'cellphone', 'money']
 if 'money' in pocket:
     pass
 else:
     print("카드를 꺼내라")

In [36]:
sum = 0
for num in range(1, 100+1) :
  sum += num
print(f'sum={sum}')

sum=5050

In [38]:
# 1~100까지 정수 중에 짝수의 합과 홀수의 합을 각각 구하시오
sumOfEven = 0
sumOfOdd = 0

for num in range(1, 101) :
  if (num%2 == 0) :
    sumOfEven += num
  else :
    sumOfOdd += num

print(f'sumOfEven={sumOfEven}')
print(f'sumOfOdd={sumOfOdd}')

sumOfEven=2550
sumOfOdd=2500

In [42]:
# 구구단 출력하기 2~9단까지 중첩 for문 이용, f'' 사용
for dan in range(2, 9+1):
  print(f'=={dan}단 출력==')
  for num in range(1, 9+1):
    print(f'{dan:2} * {num:2}={dan*num:2}')

==2단 출력==
 2 *  1= 2
 2 *  2= 4
 2 *  3= 6
 2 *  4= 8
 2 *  5=10
 2 *  6=12
 2 *  7=14
 2 *  8=16
 2 *  9=18
==3단 출력==
 3 *  1= 3
 3 *  2= 6
 3 *  3= 9
 3 *  4=12
 3 *  5=15
 3 *  6=18
 3 *  7=21
 3 *  8=24
 3 *  9=27
==4단 출력==
 4 *  1= 4
 4 *  2= 8
 4 *  3=12
 4 *  4=16
 4 *  5=20
 4 *  6=24
 4 *  7=28
 4 *  8=32
 4 *  9=36
==5단 출력==
 5 *  1= 5
 5 *  2=10
 5 *  3=15
 5 *  4=20
 5 *  5=25
 5 *  6=30
 5 *  7=35
 5 *  8=40
 5 *  9=45
==6단 출력==
 6 *  1= 6
 6 *  2=12
 6 *  3=18
 6 *  4=24
 6 *  5=30
 6 *  6=36
 6 *  7=42
 6 *  8=48
 6 *  9=54
==7단 출력==
 7 *  1= 7
 7 *  2=14
 7 *  3=21
 7 *  4=28
 7 *  5=35
 7 *  6=42
 7 *  7=49
 7 *  8=56
 7 *  9=63
==8단 출력==
 8 *  1= 8
 8 *  2=16
 8 *  3=24
 8 *  4=32
 8 *  5=40
 8 *  6=48
 8 *  7=56
 8 *  8=64
 8 *  9=72
==9단 출력==
 9 *  1= 9
 9 *  2=18
 9 *  3=27
 9 *  4=36
 9 *  5=45
 9 *  6=54
 9 *  7=63
 9 *  8=72
 9 *  9=81

In [50]:
# 단수를 입력받아 해당 구구단을 출력하시오

dansu = int(input('단수를 입력하세요 : '));
# print(type(dansu))

for num in range(1, 9+1):
  print(f'{dansu} * {num} = {dansu * num:>2} ')
# > : 오른쪽 정렬, < : 왼쪽 정렬, ^ : 가운데 정렬, :2 : 두자릿수 자리 정렬

단수를 입력하세요 : 5
5 * 1 =  5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45

In [53]:
def sum_all(*args):
  print(type(args))

  for ele in args :
    print(ele)


sum_all(1, 2, 3)

<class 'tuple'>
1
2
3

In [61]:
# 가변인자 *:튜플, **:딕셔너리
def sum_all2(*args1, **args2):
  print(type(args1))
  print(type(args2))

  for ele in args1 :
    print(ele)

  for key, val in args2.items():
    print(key, val)

# case1)
sum_all2(1, 2, 3, name='홍길동', age=10, gender='남자')

# case2)
x = (1, 2, 3)
y = {'name':'홍길동', 'age':10, 'gender':'남자'}
sum_all2(*x, **y)

<class 'tuple'>
<class 'dict'>
1
2
3
name 홍길동
age 10
gender 남자
<class 'tuple'>
<class 'dict'>
1
2
3
name 홍길동
age 10
gender 남자

In [66]:
g_var = 100 # 전역 변수 : 함수 밖에 선언된 변수
def f(p_var=300): # 매개 변수 : 함수 내에서 지녁 변수처럼 사용
  i_var = 200 # 로컬 변수 : 함수 내에 선언된 변수
  global g_var

  print(g_var)

  g_var = 400

  print(g_var)
  print(p_var)
  print(i_var)

f()

100
400
300
200

In [69]:
def sum(x, y):
  return x + y
print (sum(10, 20))

sum2 = lambda x, y : x + y
print (sum2(20, 30))

30
50

In [72]:
list2 = [1, 2, 3]
list3 = []
for ele in list:
  list3.append(ele*2)

print(list3)

def f(x):
  return x * 2

result = map(lambda x : x * 2, list2)
for ele in result:
  print(ele)

result2 = map(f, list2)
for ele in result2:
  print(ele)

[2, 4, 6]
2
4
6
2
4
6

In [75]:
f = open("test.txt", 'w')
for i in range(1, 11):
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')